import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import TanstackQueryProviders from "@/lib/provider/tanstack-query";
import { Suspense } from "react";
import { AppProgressBar } from "@/components/atoms/progressBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "IT Herca Group",
  description: "Generated by teddir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TanstackQueryProviders>{children}</TanstackQueryProviders>
        <Suspense>
          <AppProgressBar
            height="4px"
            options={{ showSpinner: false }}
            shallowRouting
          />
        </Suspense>
      </body>

    </html>
  );
}
